import { Montserrat } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // adjust weights to what you actually use
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
